spring:
  profiles:
    # 默认 dev 环境
    active: dev
  application:
    name: oj-backend-gateway
  cloud:
    gateway:
      routes:
        - id: oj-backend-user-service  #唯一即可
          uri: lb://oj-backend-user-service  #访问的微服务注册名称、lb开启负载均衡
          predicates:
            - Path=/api/user/**  #匹配访问路径，拦截后分发给上面的服务
        - id: oj-backend-question-service
          uri: lb://oj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: oj-backend-judge-service
          uri: lb://oj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: oj-backend-interface-service
          uri: lb://oj-backend-interface-service
          predicates:
            - Path=/api/interface/**
  main:
    web-application-type: reactive