spring:
  application:
    name: oj-backend-question-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.106:8848
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj_db
    username: root
    password: 1430
    # Redis 配置
  redis:
    database: 1
    host: 192.168.1.106
    port: 6379
    timeout: 5000
    password: zhuai666!
  rabbitmq:
    host: 192.168.1.106
    port: 5672
    username: zhuai
    password: zhuai666!
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api/question
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        #设置Path，不然会出现Cookie失效
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #取消驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
#配置seata的注册中心，告诉seata client怎么去访问seate server(TC)
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.1.106:8848  #seate server所在的nacos服务地址
      application: seata-server #seate server 的服务名
      username: nacos
      password: nacos
      group: SEATA_GROUP # seate server 所在的组，默认就是SEATA_GROUP，没有改可以不用配置
  config: # 配置中心
    type: nacos
    nacos:
      server-addr: 192.168.1.106:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      # 如果是默认空间则可以不用添加
      namespace: 6c035547-fda4-4f2b-9d39-80e6ae176cda
  tx-service-group: my_test_tx_group #与seata\script\config-center\config.txt中的一致
knife4j:
  enable: true