server:
  port: 8103

knife4j:
  enable: false

spring:
  cloud:
    nacos:
      discovery:
        server-addr: XXXX:8848
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://XXXX:3306/oj_db
    username: XXXX
    password: XXXX
    # Redis 配置
  redis:
    database: 1
    host: XXXX
    port: 6379
    timeout: 5000
    password: XXXX
  rabbitmq:
    host: XXXX
    port: 5672
    username: XXXX
    password: XXXX

#配置seata的注册中心，告诉seata client怎么去访问seate server(TC)
seata:
  registry:
    type: nacos
    nacos:
      server-addr: XXXX:8848  #seate server所在的nacos服务地址
      application: seata-server #seate server 的服务名
      username: nacos
      password: nacos
      group: SEATA_GROUP # seate server 所在的组，默认就是SEATA_GROUP，没有改可以不用配置
  config: # 配置中心
    type: nacos
    nacos:
      server-addr: XXXX:8848
      username: nacos
      password: nacos
      group: XXXX #例：SEATA_GROUP
      # 如果是默认空间则可以不用添加
      namespace: XXXX #例：6c035547-fda4-4f2b-9d39-80e6ae176cda
  tx-service-group: XXXX #例：my_test_tx_group  与seata\script\config-center\config.txt中的一致